@rootAPI = http://localhost:8000/api/v1


# ====== admin api =======

###get Admin
GET {{rootAPI}}/admin

# ========== product api =======
###get product
GET  {{rootAPI}}/product


# ============ payment =============
### get method
GET {{rootAPI}}/payment

### POST payment
POST {{rootAPI}}/payment
Content-Type: application/json

{
    "amount": "240",
    "currency": "AUD",
    "paymentMethodType": "Card"
}